# Generated by Django 4.1.4 on 2022-12-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_002', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='end_year',
            field=models.IntegerField(default=None),
        ),
    ]
