# Generated by Django 4.1.4 on 2022-12-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_002', '0002_musician_end_year'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table='musicians',
        ),
    ]
