# Generated by Django 4.1.4 on 2022-12-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_002', '0003_alter_musician_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='end_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
