# Generated by Django 4.1.4 on 2022-12-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_002', '0004_alter_musician_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='end_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
